import random
portmanteaus = {
    'Hybrids': {
        'cattalo': ('cattle', 'buffalo'),
        'donkra': ('donkey', 'zebra'),
        'llamanaco': ('llama', 'guanaco'),
        'wholphin': ('whale', 'dolphin'),
        'zorse': ('zebra', 'horse')
    },
    'Cats': {
        'leopon': ('leopard', 'lion'),
        'liger': ('lion', 'tiger'),
        'tigon': ('tiger', 'lion')
    },
    'Mixed Breeds - Dogs': {
        'cockapoo': ('cocker spaniel', 'poodle'),
        'goldendoodle': ('golden retriever', 'poodle'),
        'Labradoodle': ('Labrador retriever', 'poodle')
    },
    'Mixed Breeds - Other': {
        'beefalo': ('beef', 'buffalo'),
        'Brangus': ('Brahman', 'Angus'),
        'Wangus': ('Wagyu', 'Angus'),
    },
    'Characteristics': {
        'camelopard': ('camel', 'leopard'),
        'Beelzebufo': ('Beelzebub', 'Bufo'),
        'sploot': ('splay', 'scoot'),
        'squitten': ('squirrel', 'kitten'),
    },
    'Fictional': {
        'Aristocats': ('aristocrats', 'cats'),
        'buggalo': ('bug', 'buffalo'),
        'crocoduck': ('crocodile', 'duck'),
        'jackalope': ('jackrabbit', 'antelope'),
        'mammophant': ('mammoth', 'elephant'),
        'pegacorn': ('Pegasus', 'unicorn'),
        'Pigasus': ('pig', 'Pegasus'),
        'Predalien': ('Predator', 'Alien'),
        'Squirtle': ('squirt', 'turtle')
    },
    'Art, Literature, and Entertainment': {
        'animatronics': ('animation', 'electronics'),
        'Barbenheimer': ('Barbie', 'Oppenheimer'),
        'batarang': ('bat', 'boomerang'),
        'Bennifer': ('Ben Affleck', 'Jennifer Lopez'),
        'blaxploitation': ('black', 'exploitation'),
        'Bollywood': ('Bombay', 'Hollywood'),
        'Bootylicious': ('booty', 'delicious'),
        'Brangelina': ('Brad Pitt', 'Angelina Jolie'),
        'bromance': ('bro', 'romance'),
        'Brony': ('bro', 'pony'),
        'Californication': ('California', 'fornication'),
        'Chamillionaire': ('chameleon', 'millionaire'),
        'Death \'n\' roll': ('death metal', 'rock \'n\' roll'),
        'disasterpiece': ('disaster', 'masterpiece'),
        'disemvoweling': ('disemboweling', 'vowel'),
        'Dhallywood': ('Dhaka', 'Hollywood'),
        'docudrama': ('documentary', 'drama'),
        'docuseries': ('documentary', 'series'),
        'docusoap': ('documentary', 'soap opera'),
        'Dollywood': ('Dolly Parton', 'Hollywood'),
        'Draculaura': ('Dracula', 'Laura'),
        'dramedy': ('drama', 'comedy'),
        'edutainment': ('education', 'entertainment'),
        'Electrocutioner': ('electrocution', 'executioner'),
        'faction': ('fact', 'fiction'),
        'fanac': ('fan', 'activity'),
        'fanslation': ('fan', 'translation'),
        'fanzine': ('fan', 'magazine'),
        'fauxligraphy': ('faux', 'calligraphy'),
        'fauxlography': ('faux', 'holography'),
        'fauxtography': ('faux', 'photography'),
        'FUNimation': ('fun', 'animation'),
        'Funkadelic': ('funk', 'psychedelic'),
        'Galentine\'s Day': ('gals', 'Valentine\'s Day'),
        'Gleeks': ('Glee', 'geeks'),
        'glitterati': ('glitter', 'literati'),
        'Governator': ('governor', 'Terminator'),
        'Gojira': ('gorilla', 'whale'),
        'Görliwood': ('Görlitz', 'Hollywood'),
        'greige': ('grey', 'beige'),
        'grue': ('green', 'blue'),
        'Hamburglar': ('hamburger', 'burglar'),
        'Hatchimals': ('hatch', 'animals'),
        'ignorati': ('ignorant', 'literati'),
        'infomercial': ('information', 'commercial'),
        'infotainment': ('information', 'entertainment'),
        'Jamiroquai': ('Jam (session)', 'Iroquois'),
        'Japandroids': ('Japanese Scream', 'Pleasure Droids'),
        'Japanoise': ('Japanese', 'noise'),
        'Jedward': ('John', 'Edward Grimes'),
        'Jollywood': ('Jyoti Chitraban Film Studio', 'Hollywood'),
        'Kollywood': ('Kodambakkam', 'Hollywood'),
        'Kripkenstein': ('Saul Kripke', 'Ludwig Wittgenstein'),
        'latensification': ('latent', 'intensification'),
        'literotica': ('literature', 'erotica'),
        'Lollywood': ('Lahore', 'Hollywood'),
        'machinima': ('machine', 'cinema'),
        'Mandroid': ('man', 'android'),
        'Megxit': ('Meghan', 'exit'),
        'Metroidvania': ('Metroid', 'Castlevania'),
        'Mephiskapheles': ('Mephistopheles', 'ska'),
        'militainment': ('military', 'entertainment'),
        'mockbuster': ('mock', 'blockbuster'),
        'mockumentary': ('mock', 'documentary'),
        'Mollywood': ('Malayalam', 'Marathi', 'Mormon'),
        'Monokuma': ('monochrome', 'Japanese kuma'),
        'Mouseketeer': ('Mickey Mouse', 'musketeer'),
        'Muppet': ('marionette', 'puppet'),
        'newscast': ('news', 'broadcast'),
        'Nedna': ('Ned Flanders', 'Edna Krabappel'),
        'Ninjago': ('ninja', 'Lego'),
        'Nollywood': ('Nigeria', 'Hollywood'),
        'nonebrity': ('nonentity', 'celebrity'),
        'Odditorium': ('odd', 'auditorium'),
        'Ollywood': ('Odia', 'Hollywood'),
        'Pallywood': ('Palestinian', 'Hollywood'),
        'Parcheesi': ('Parker Brothers', 'pachisi'),
        'Pensieve': ('pensive', 'sieve'),
        'presstitutes': ('press', 'prostitutes'),
        'prequiem': ('preemptive', 'requiem'),
        'psychobilly': ('psycho', 'rockabilly'),
        'rainscaping': ('rain', 'landscaping'),
        'reprography': ('reproduce', 'photography'),
        'rockabilly': ('rock', 'hillbilly'),
        'rockumentary': ('rock', 'documentary'),
        'scanlation': ('scan', 'translation'),
        'schlockumentary': ('schlock', 'documentary'),
        'seascape': ('sea', 'landscape'),
        'sextra': ('sex', 'extra'),
        'shockumentary': ('shock', 'documentary'),
        'showmance': ('show business', 'romance'),
        'sidequel': ('side', 'sequel'),
        'Siliwood': ('Silicon Valley', 'Hollywood'),
        'skinema': ('skin', 'cinema'),
        'Skinemax': ('skin', 'Cinemax'),
        'Slingo': ('slots', 'bingo'),
        'smark': ('smart', 'mark'),
        'soundscape': ('sound', 'landscape'),
        'Spraycation': ('vacation', 'spraypainting'),
        'Stucky': ('Steve Rogers', 'Bucky Barnes'),
        'Tamagotchi': ('tamago', 'uotchi'),
        'telegenic': ('television', 'photogenic'),
        'teleidoscope': ('telescope', 'kaleidoscope'),
        'televangelist': ('television', 'evangelist'),
        'Tollywood': ('Tollygunge', 'Telugu', 'Hollywood'),
        'TomKat': ('Tom Cruise', 'Katie Holmes'),
        'tragicomedy': ('tragedy', 'comedy'),
        'Treknology': ('Star Trek', 'technology'),
        'Truckasaurus': ('truck', 'Tyrannosaurus'),
        'Unwindulax': ('unwind', 'relax'),
        'Valleywood': ('Wye Valley', 'Hollywood'),
        'Wagatha Christie': ('WAGs', 'Agatha Christie'),
        'Waluigi': ('warui', 'Luigi'),
        'Wario': ('warui', 'Mario'),
        'Wellywood': ('Wellington', 'Hollywood')
    },
    'Fashion and Apparel': {
        'anklet': ('ankle', 'bracelet'),
        'armlet': ('arm', 'bracelet'),
        'bandkini': ('bandeau', 'bikini'),
        'burkini': ('burka', 'bikini'),
        'camikini': ('camisole', 'bikini'),
        'cosplay': ('costume', 'roleplay'),
        'crossplay': ('crossdressing', 'cosplay'),
        'dayjamas': ('daytime', 'pajamas'),
        'draids': ('dreadlocks', 'braids'),
        'facekini': ('face', 'bikini'),
        'fauxhawk': ('faux', 'mohawk'),
        'femullet': ('female', 'mullet'),
        'flagkini': ('flag', 'bikini'),
        'floordrobe': ('floor', 'wardrobe'),
        'glamazon': ('glamorous', 'Amazon'),
        'groutfit': ('gray', 'outfit'),
        'halterkini': ('halter top', 'bikini'),
        'jeggings': ('jeans', 'leggings'),
        'Jewfro': ('Jew', 'afro'),
        'jorts': ('jeans', 'shorts'),
        'mankini': ('man', 'bikini'),
        'manscaping': ('man', 'landscaping'),
        'manssiere': ('man', 'brassiere'),
        'manzilian': ('man', 'Brazilian wax'),
        'meggings': ('man', 'leggings'),
        'metrosexual': ('metropolitan', 'heterosexual'),
        'murse': ('man', 'purse'),
        'Nair': ('no', 'hair'),
        'pleather': ('plastic', 'leather'),
        'pubikini': ('pubic', 'bikini'),
        'seekini': ('see-through', 'bikini'),
        'shaxing': ('shaving', 'waxing'),
        'skirtini': ('skirt', 'bikini'),
        'skort': ('skirt', 'short'),
        'skullet': ('skull', 'mullet'),
        'slingkini': ('slingshot', 'bikini'),
        'starburns': ('star', 'sideburns'),
        'stringkini': ('string', 'bikini'),
        'tactleneck': ('tactical', 'turtleneck'),
        'tankini': ('tank top', 'bikini'),
        'tanorexia': ('tan', 'anorexia'),
        'tantoo': ('tan', 'tattoo'),
        'tapekini': ('tape', 'bikini'),
        'treggings': ('trousers', 'leggings'),
        'trikini': ('triple', 'bikini'),
        'vabbing': ('vagina', 'dabbing'),
        'vajazzle': ('vagina', 'bedazzle'),
        'vajungle': ('vagina', 'jungle'),
        'vattoo': ('vagina', 'tattoo'),
        'Velcro': ('velvet', 'crochet'),
    },
    'Instruments': {
        'banjitar': ('banjo', 'guitar'),
        'banjolele': ('banjo', 'ukulele'),
        'banjolin': ('banjo', 'mandolin'),
        'escopetarra': ('escopeta', 'guitarra'),
        'flumpet': ('flugelhorn', 'trumpet'),
        'guitalele': ('guitar', 'ukulele'),
        'guitalin': ('guitar', 'mandolin'),
        'keytar': ('keyboard', 'guitar'),
        'sympitar': ('sympathetic string', 'guitar'),
        'tromboon': ('trombone', 'bassoon'),
        'ukelin': ('ukulele', 'violin'),
    },
    'Titles': {
        'Alphabear': ('alphabet', 'bear'),
        'Animaniacs': ('animated', 'maniacs'),
        'Animatrix': ('anime', 'The Matrix'),
        'Animorphs': ('animal', 'morphers'),
        'Banjo-Tooie': ('Banjo-Kazooie', 'two'),
        'BASEketball': ('baseball', 'basketball'),
        'The Beverly Hillbillies': ('Beverly Hills', 'hillbillies'),
        'Blacula': ('black', 'Dracula'),
        'Bunnicula': ('bunny', 'Dracula'),
        'Castlevania': ('castle', 'Transylvania'),
        'Crooklyn': ('crook', 'Brooklyn'),
        'Disturbia': ('disturbed', 'suburbia'),
        'Ennuigi': ('ennui', 'Luigi'),
        'ElimiDate': ('eliminate', 'date'),
        'Evilution': ('evil', 'evolution'),
        'Fergalicious': ('Fergie', 'delicious'),
        'Floribama Shore': ('Florida', 'Alabama'),
        'Frankenfish': ('Frankenstein', 'fish'),
        'Funderdome': ('funding', 'Thunderdome'),
        'Incognegro': ('incognito', 'negro'),
        'Instrumedley': ('instrument', 'medley'),
        'Lamprophrenia': ('lampron', 'phrenia'),
        'Lavalantula': ('lava', 'tarantula'),
        'Manimal': ('man', 'animal'),
        'Manster': ('man', 'monster'),
        'MANswers': ('man', 'answers'),
        'Menergy': ('men', 'energy'),
        'Morroblivion': ('Morrowind', 'Oblivion'),
        'Mutanimals': ('mutant', 'animals'),
        'Nintendogs': ('Nintendo', 'dogs'),
        'Notzilla': ('not', 'Godzilla'),
        'Piranhaconda': ('piranha', 'anaconda'),
        'Plandemic': ('plan', 'pandemic'),
        'Policenauts': ('police', 'astronaut'),
        'Polygondwanaland': ('polygon', 'Gondwanaland'),
        'Pornograffitti': ('pornography', 'graffiti'),
        'Puppetoons': ('puppets', 'cartoons'),
        'Quantumania': ('quantum', 'mania'),
        'Religulous': ('religion', 'ridiculous'),
        'Returnal': ('return', 'eternal'),
        'Revolusongs': ('revolution', 'songs'),
        'Roblox': ('robot', 'blocks'),
        'Scribblenauts': ('scribble', 'astronauts'),
        'Seaspiracy': ('sea', 'conspiracy'),
        'Seussical': ('Dr. Seuss', 'musical'),
        'Sharknado': ('shark', 'tornado'),
        'Sharktopus': ('shark', 'octopus'),
        'Sidetalk': ('sidewalk', 'talk'),
        'Simpsorama': ('The Simpsons', 'Futurama'),
        'Skyblivion': ('The Elder Scrolls V: Skyrim', 'The Elder Scrolls IV: Oblivion'),
        'Skywind': ('The Elder Scrolls V: Skyrim', 'Morrowind'),
        'Somari': ('Sonic the Hedgehog', 'Mario'),
        'Spamalot': ('Spam', 'Camelot'),
        'SPAMasterpiece Theater': ('SPAM', 'Masterpiece Theater'),
        'Splatoon': ('splat', 'platoon'),
        'Spontaneanation': ('spontaneous', 'nation'),
        'Talkartoons': ('talk', 'cartoons'),
        'ThanksKilling': ('Thanksgiving', 'killing'),
        'Threatmantics': ('threatening', 'romantics'),
        'Undertale': ('underground', 'Fairy tale'),
        'Vandread': ('vanguard', 'dreadnought'),
        'VelociPastor': ('Velociraptor', 'pastor'),
        'Workaholics': ('work', 'alcoholics'),
        'Zombeavers': ('zombie', 'beavers'),
        'Zoombies': ('zoo', 'zombies'),
        'Zootopia': ('zoo', 'utopia'),
    },

    'Cuisine': {
        'bananacue': ('banana', 'barbecue'),
        'banilla': ('banana', 'vanilla'),
        'banoffee': ('banana', 'toffee'),
        'banoodles': ('bananas', 'noodles'),
        'barcade': ('bar', 'arcade'),
        'beefaroni': ('beef', 'macaroni'),
        'beerage': ('beer', 'peerage'),
        'Bisquick': ('biscuit', 'quick'),
        'broast': ('broil', 'roast'),
        'brunch': ('breakfast', 'lunch'),
        'Buffaranch': ('Buffalo sauce', 'ranch dressing'),
        'camotecue': ('Spanish camote', 'barbecue'),
        'cannabutter': ('cannabis', 'butter'),
        'Canola': ('Canadian oil', 'low acid'),
        'chookie': ('cheesecake', 'cookie'),
        'chork': ('chopsticks', 'fork'),
        'Cinnabon': ('cinnamon', 'bun'),
        'crabocado': ('crab', 'avocado'),
        'Craisin': ('cranberry', 'raisin'),
        'CremeSavers': ('creme', 'Lifesavers'),
        'Croissan\'wich': ('croissant', 'sandwich'),
        'cronut': ('croissant', 'doughnut'),
        'Dijonnaise': ('Dijon', 'mayonnaise'),
        'dunch': ('dinner', 'lunch'),
        'Dunkaroos': ('dunk', 'kangaroos'),
        'enchalupa': ('enchilada', 'chalupa'),
        'Enchirito': ('enchilada', 'burrito'),
        'Fabanaise': ('aquafaba', 'mayonnaise'),
        'facon': ('fake', 'bacon'),
        'fawaffle': ('falafel', 'waffle'),
        'flavorite': ('flavor', 'favorite'),
        'flexitarian': ('flexible', 'vegetarian'),
        'freeganism': ('free', 'veganism'),
        'froyo': ('frozen', 'yogurt'),
        'Funfetti': ('fun', 'confetti'),
        'Funyuns': ('fun', 'onions'),
        'gastropub': ('gastronomy', 'public house'),
        'glutose': ('glucose', 'fructose'),
        'Gogurt': ('go', 'yogurt'),
        'Hanch': ('hot sauce', 'ranch dressing'),
        'Honeyracha': ('honey', 'sriracha'),
        'hufu': ('human', 'tofu'),
        'insinkerator': ('sink', 'incinerator'),
        'jizzcuit': ('jizz', 'biscuit'),
        'Ketchili': ('ketchup', 'sweet chili sauce'),
        'knork': ('knife', 'fork'),
        'Kranch': ('ketchup', 'ranch dressing'),
        'linner': ('lunch', 'dinner'),
        'Lymon': ('lime', 'lemon'),
        'Manwich': ('man', 'sandwich'),
        'Mayochup': ('mayonnaise', 'ketchup'),
        'Mayocue': ('mayonnaise', 'barbecue'),
        'Mayomust': ('mayonnaise', 'mustard'),
        'Mayoracha': ('mayonnaise', 'sriracha'),
        'menma': ('ramen', 'machiku'),
        'pizzone': ('pizza', 'calzone'),
        'popsicle': ('pop', 'icicle'),
        'quesalupa': ('quesadilla', 'chalupa'),
        'quesarito': ('quesadilla', 'burrito'),
        'Rice-A-Roni': ('rice', 'macaroni'),
        'salsamole': ('alsa', 'guacamole'),
        'scromlette': ('scrambled eggs', 'omelette'),
        'snaccident': ('snack', 'accident'),
        'soylent': ('soy', 'lentil'),
        'soysage': ('soy', 'sausage'),
        'spatchcock': ('dispatch', 'cock'),
        'spife': ('spoon', 'knife'),
        'spoodle': ('spoon', 'ladle'),
        'sporf': ('spoon', 'fork', 'knife'),
        'spork': ('spoon', 'fork'),
        'sujeo': ('Korean sutgarak', 'jeotgarak'),
        'Tarchup': ('tartar sauce', 'ketchup'),
        'tofurkey': ('tofu', 'turkey'),
        'totchos': ('tater tots', 'nachos'),
        'turducken': ('turkey', 'duck', 'chicken'),
        'Vegenaise': ('vegan', 'mayonnaise'),
        'Wasabioli': ('wasabi', 'aioli'),
        'zoodles': ('zucchini', 'noodles'),
    },
    'Beverages': {
        'alcopop': ('alcohol', 'pop'),
        'appletini': ('apple', 'martini'),
        'beergarita': ('beer', 'margarita'),
        'bluberrita': ('blueberry', 'margarita'),
        'Clamato': ('clam', 'tomato juice'),
        'Coco Rico': ('coconut', 'Puerto Rico'),
        'coffeetini': ('coffee', 'martini'),
        'cranberrita': ('cranberry', 'margarita'),
        'crantini': ('cranberry', 'martini'),
        'dollaritas': ('dollar', 'margaritas'),
        'flirtini': ('flirt', 'martini'),
        'frappuccino': ('frappé', 'cappuccino'),
        'gelatini': ('gelatin', 'martini'),
        'kegerator': ('keg', 'refrigerator'),
        'mangorita': ('mango', 'margarita'),
        'Meritage': ('merit', 'heritage'),
        'mocktail': ('mock', 'cocktail'),
        'Nespresso': ('Nestlé', 'espresso'),
        'Palcohol': ('powder', 'alcohol'),
        'raspberrita': ('raspberry', 'margarita'),
        'rumchata': ('spiced rum', 'horchata'),
        'saketini': ('sake', 'martini'),
        'scotchka': ('scotch', 'vodka'),
        'seltzerita': ('hard seltzer', 'margarita'),
        'Silk': ('soy', 'milk'),
        'strawberrita': ('strawberry', 'margarita'),
        'vodkatini': ('vodka', 'martini'),
    },
    'Hybrids': {
        'broccoflower': ('broccoli', 'cauliflower'),
        'Brusselkale': ('Brussels sprouts', 'kale'),
        'caulini': ('cauliflower', 'broccolini'),
        'celtuce': ('celery', 'lettuce'),
        'citrange': ('citron', 'orange'),
        'citrangequat': ('citrange', 'kumquat'),
        'citrumelo': ('citrus', 'pommelo'),
        'garlion': ('garlic', 'onion'),
        'Grāpple': ('grape', 'apple'),
        'Kinnow': ('King', 'Willow Leaf'),
        'lemonquat': ('lemon', 'kumquat'),
        'limequat': ('Key lime', 'kumquat'),
        'mandelo': ('mandarin orange', 'pommelo'),
        'orangequat': ('orange', 'kumquat'),
        'parsnip': ('Pastinaca', 'turnip'),
        'peacherine': ('peach', 'nectarine'),
        'peacotum': ('peach', 'apricot', 'plum'),
        'pineberry': ('pineapple', 'strawberry'),
        'pluot': ('plum', 'apricot'),
        'pomato': ('potato', 'tomato'),
        'procimequat': ('primitive Hong Kong kumquat', 'limequat'),
        'sunchoke': ('sunflower', 'artichoke'),
        'tangelo': ('tangerine', 'pomelo'),
        'tomacco': ('tomato', 'tobacco'),
        'topepo': ('tomato', 'sweet pepper'),
        'triticale': ('Triticum', 'Secale'),
        'yuzuquat': ('yuzu', 'kumquat'),
    },
    'Fashion': {
        'Aberzombie': ('Abercrombie', 'zombie'),
        'broseph': ('bro', 'Joseph'),
        'brosephine': ('bro', 'Josephine'),
        'fashletic': ('fashion', 'athletic'),
        'fugly': ('funky', 'ugly'),
        'glamourpuss': ('glamour', 'pussycat'),
        'hipatetic': ('hipster', 'pathetic'),
        'Nauticaunt': ('nautical', 'aunt'),
        'prepster': ('preppy', 'hipster'),
        'sheeple': ('sheep', 'people'),
        'twunk': ('twink', 'hunk'),
        'wuss': ('wimp', 'puss'),
    },
    'Technology': {
        'botel': ('boat', 'hotel'),
        'brainiac': ('brain', 'maniac'),
        'cablegram': ('cable', 'telegram'),
        'camcorder': ('camera', 'recorder'),
        'cyberdelic': ('cyber', 'psychedelic'),
        'dadvice': ('dad', 'advice'),
        'electrocute': ('electric', 'execute'),
        'gamification': ('game', 'modification'),
        'gamify': ('game', 'modify'),
        'hacktivist': ('hack', 'activist'),
        'hubot': ('human', 'robot'),
        'infomercial': ('information', 'commercial'),
        'internet': ('interconnected', 'network'),
        'intexticated': ('intoxicated', 'text'),
        'malware': ('malicious', 'software'),
        'meme': ('mind', 'gene'),
        'netiquette': ('network', 'etiquette'),
        'netizen': ('internet', 'citizen'),
        'pixel': ('picture', 'element'),
        'podcast': ('iPod', 'broadcast'),
        'proximity': ('proximate', 'immunity'),
        'scanxiety': ('scan', 'anxiety'),
        'selfie': ('self', 'photograph'),
        'shareware': ('share', 'software'),
        'smexting': ('smartphone', 'texting'),
        'software': ('soft', 'hardware'),
        'spam': ('spiced', 'ham'),
        'spambot': ('spam', 'robot'),
        'spamnesty': ('spam', 'amnesty'),
        'spambulance': ('spam', 'ambulance'),
        'spampede': ('spam', 'stampede'),
        'spamnesia': ('spam', 'amnesia'),
        'spamosphere': ('spam', 'atmosphere'),
        'spamulet': ('spam', 'amulet'),
        'textpectation': ('text', 'expectation'),
        'textual': ('text', 'sexual'),
        'troll': ('trawl', 'control'),
        'trojan': ('Trojan', 'condom'),
        'vlog': ('video', 'blog'),
        'vlogmas': ('video', 'Christmas'),
        'vlogumentary': ('video', 'documentary'),
        'vlogosphere': ('video', 'atmosphere'),
        'webinar': ('web', 'seminar'),
        'webisode': ('web', 'episode'),
        'weblog': ('web', 'log'),
        'webzine': ('web', 'magazine'),
        'wiki': ('web', 'dictionary'),
        'workaholic': ('work', 'alcoholic'),
    },
    'Food': {
        'baconnaise': ('bacon', 'mayonnaise'),
        'bakeover': ('bake', 'makeover'),
        'bananacue': ('banana', 'barbecue'),
        'beerbecue': ('beer', 'barbecue'),
        'beerita': ('beer', 'margarita'),
        'beergasm': ('beer', 'orgasm'),
        'bleisure': ('business', 'leisure'),
        'brinner': ('breakfast', 'dinner'),
        'brunch': ('breakfast', 'lunch'),
        'bruschetta': ('bread', 'toasted'),
        'bruschetta': ('bread', 'toasted'),
        'burgerizza': ('burger', 'pizza'),
        'cafetorium': ('cafeteria', 'auditorium'),
        'cafetorium': ('cafeteria', 'auditorium'),
        'cakewalk': ('cake', 'walk'),
        'carbacide': ('carb', 'homicide'),
        'carbfusion': ('carb', 'confusion'),
        'cheeseburger': ('cheese', 'burger'),
        'chickenetarian': ('chicken', 'vegetarian'),
        'chillax': ('chill', 'relax'),
        'chocoholic': ('chocolate', 'alcoholic'),
        'chug': ('chew', 'lug'),
        'chugger': ('chew', 'lugger'),
        'churrascaria': ('churrasco', 'barbecue'),
        'coffice': ('coffee', 'office'),
        'confectionery': ('confection', 'eatery'),
        'cookout': ('cook', 'out'),
        'cravings': ('crave', 'longings'),
        'cronut': ('croissant', 'doughnut'),
        'cupcake': ('cup', 'cake'),
        'dairyness': ('dairy', 'happiness'),
        'delish': ('delightful', 'delicious'),
        'drinkware': ('drink', 'tableware'),
        'edible': ('eat', 'able'),
        'eatathon': ('eat', 'marathon'),
        'eatery': ('eat', 'ery'),
        'enjoyliday': ('enjoy', 'holiday'),
        'fabanaise': ('aquafaba', 'mayonnaise'),
        'facon': ('fake', 'bacon'),
        'fawaffle': ('falafel', 'waffle'),
        'foodie': ('food', 'hoodie'),
        'foodventure': ('food', 'adventure'),
        'foodzilla': ('food', 'Godzilla'),
        'fro-yo': ('frozen', 'yogurt'),
        'gluttony': ('glutton', 'luxury'),
        'gourmandize': ('gourmet', 'prize'),
        'grubhub': ('grub', 'hub'),
        'hangry': ('hungry', 'angry'),
        'impressario': ('impress', 'impresario'),
        'junketarian': ('junk food', 'vegetarian'),
        'kaleidoscope': ('kale', 'scope'),
        'macarons': ('macaroon', 'macaroni'),
        'manwich': ('man', 'sandwich'),
        'muffin-top': ('muffin', 'top'),
        'naanwich': ('naan', 'sandwich'),
        'nosh': ('nibble', 'gobble'),
        'omelette': ('omelet', 'omelette'),
        'overeaters': ('overeat', 'eatery'),
        'pastariffic': ('pasta', 'terrific'),
        'pastrami': ('pastry', 'salami'),
        'pizzaghetti': ('pizza', 'spaghetti'),
        'popcorn': ('pop', 'corn'),
        'pretzelvania': ('pretzel', 'Pennsylvania'),
        'quaff': ('quench', 'laugh'),
        'ramen': ('raw', 'men'),
        'refreshments': ('refresh', 'refreshments'),
        'respresso': ('restaurant', 'espresso'),
        'roomance': ('room', 'romance'),
        'saucery': ('sauce', 'sorcery'),
        'sausagedog': ('sausage', 'dog'),
        'savory': ('satisfying', 'flavorful'),
        'sipple': ('sip', 'nibble'),
        'snacket': ('snack', 'packet'),
        'snacktastic': ('snack', 'fantastic'),
        'spud': ('spear', 'mud'),
        'spudnut': ('spud', 'nut'),
        'sushi': ('raw', 'fish'),
        'sweetle': ('sweet', 'beetle'),
        'taco': ('tortilla', 'sandwich'),
        'tasteful': ('tasty', 'beautiful'),
        'tasting': ('taste', 'testing'),
        'teaf': ('tea', 'leaf'),
        'tea-ism': ('tea', 'alcoholism'),
        'thirstea': ('thirst', 'tea'),
        'titbits': ('titillating', 'tidbits'),
        'treatza': ('treat', 'pizza'),
        'tropically': ('tropical', 'epically'),
        'turducken': ('turkey', 'duck', 'chicken'),
        'vodka': ('vodka', 'soda'),
        'vodkatini': ('vodka', 'martini'),
        'waffle': ('waffle', 'shuffle'),
        'winery': ('wine', 'ery'),
        'yogurt': ('yogurt', 'tart'),
    },
    'Hybrids': {
        'beerita': ('beer', 'margarita'),
        'broseph': ('bro', 'Joseph'),
        'brosephine': ('bro', 'Josephine'),
        'brunch': ('breakfast', 'lunch'),
        'camcorder': ('camera', 'recorder'),
        'fashletic': ('fashion', 'athletic'),
        'gamification': ('game', 'modification'),
        'hacktivist': ('hack', 'activist'),
        'malware': ('malicious', 'software'),
        'manwich': ('man', 'sandwich'),
        'netiquette': ('network', 'etiquette'),
        'prebuttal': ('preemptive', 'rebuttal'),
        'spork': ('spoon', 'fork'),
        'textual': ('text', 'sexual'),
        'twerk': ('twist', 'jerk'),
        'twunk': ('twink', 'hunk'),
        'vlog': ('video', 'blog'),
        'webinar': ('web', 'seminar'),
        'webisode': ('web', 'episode'),
        'workaholic': ('work', 'alcoholic'),
        'workiversary': ('work', 'anniversary'),
        'wuss': ('wimp', 'puss'),
    },
    'Internet and Computing': {
        'alphanumeric': ('alphabetic', 'numeric'),
        'ASCIIbetical': ('ASCII', 'alphabetical'),
        'balun': ('balanced', 'unbalanced'),
        'bitmoji': ('bit', 'emoji'),
        'blogosphere': ('blog', 'logosphere'),
        'blorph': ('blend', 'morph'),
        'brogrammer': ('bro', 'programmer'),
        'brouter': ('bridge', 'router'),
        'bullshot': ('bullshit', 'screenshot'),
        'Chaturbate': ('chat', 'masturbate'),
        'codec': ('coder', 'decoder'),
        'companding': ('compressing', 'expanding'),
        'concolic': ('concrete', 'symbolic'),
        'cryptography': ('hidden', 'writing'),
        'cryptocurrency': ('cryptography', 'currency'),
        'cybrarian': ('cyber', 'librarian'),
        'Darwine': ('Darwin', 'WINE'),
        'debconf': ('Debian', 'configuration'),
        'datacasting': ('data', 'broadcasting'),
        'dataveillance': ('data', 'surveillance'),
        'deepfake': ('deep learning', 'fake'),
        'desknote': ('desktop', 'notebook'),
        'digerati': ('digital', 'literati'),
        'emoticon': ('emotion', 'icon'),
        'favicon': ('favourite', 'icon'),
        'Fediverse': ('federation', 'universe'),
        'Finsta': ('fake', 'Instagram'),
        'folksonomy': ('folk', 'taxonomy'),
        'frecency': ('frequency', 'recency'),
        'freemium': ('free', 'premium'),
        'Hackintosh': ('hack', 'Macintosh'),
        'hacktivism': ('hack', 'activism'),
        'Hatreon': ('hate', 'Patreon'),
        'incel': ('involuntary', 'celibate'),
        'Intellivision': ('intelligent', 'television'),
        'Joy-Con': ('joystick', 'controller'),
        'Jython': ('Java', 'Python'),
        'Kinect': ('kinetic', 'connection'),
        'knowledgebase': ('knowledge', 'database'),
        'Linux': ('Linus', 'Unix'),
        'listicle': ('list', 'article'),
        'Mactel': ('Macintosh', 'Intel'),
        'Markiplier': ('Mark', 'multiplier'),
        'memex': ('memory', 'index'),
        'Mii': ('Wii', 'me'),
        'Mobilegeddon': ('mobile', 'Armageddon'),
        'modem': ('modulator', 'demodulator'),
        'modmin': ('moderator', 'admin'),
        'Mozilla': ('mosaic killer', 'Godzilla'),
        'netiquette': ('Internet', 'etiquette'),
        'netizen': ('(Inter)net', 'citizen'),
        'phablet': ('phone', 'tablet'),
        'pharming': ('phishing', 'farming'),
        'phubbing': ('phone', 'snubbing'),
        'pixel': ('picture', 'element'),
        'podcast': ('iPod', 'broadcast'),
        'Privoxy': ('privacy', 'proxy'),
        'Project Chanology': ('chan', 'Scientology'),
        'QAnonsense': ('QAnon', 'nonsense'),
        'Raspbian': ('Raspberry Pi', 'Debian'),
        'reddiquette': ('Reddit', 'etiquette'),
        'resel': ('resolution', 'element'),
        'screenager': ('screen', 'teenager'),
        'screenshot': ('screen', 'snapshot'),
        'SerDes': ('serialize', 'deserialize'),
        'Skype': ('sky', 'peer-to-peer'),
        'spamdexing': ('spam', 'indexing'),
        'spamouflage': ('spam', 'camouflage'),
        'spaxel': ('spatial', 'pixel'),
        'sporgery': ('spam', 'forgery'),
        'texel': ('texture', 'element'),
        'textonym': ('text', 'synonym'),
        'Throwbot': ('throw', 'robot'),
        'treap': ('tree', 'heap'),
        'trixel': ('triangle', 'pixel'),
        'Twitterverse': ('Twitter', 'universe'),
        'upsert': ('update', 'insert'),
        'vlog': ('video', 'blog'),
        'vortal': ('vertical', 'portal'),
        'voxel': ('volume', 'pixel'),
        'wardriving': ('wardialing', 'driving'),
        'webcast': ('World Wide Web', 'broadcast'),
        'webinar': ('World Wide Web', 'seminar'),
        'webisode': ('World Wide Web', 'episode'),
        'webtoon': ('World Wide Web', 'cartoon'),
        'widget': ('window', 'gadget'),
        'Wikipedia': ('wiki', 'encyclopedia'),
        'Wintel': ('Windows', 'Intel'),
    },
    'Marketing': {
        'advertainment': ('advertising', 'entertainment'),
        'advertorial': ('advertising', 'editorial'),
        'entreporn': ('entrepreneur', 'porn'),
        'innoventing': ('innovating', 'inventing'),
        'marchitecture': ('marketing', 'architecture'),
        'cineplex': ('cinema', 'complex'),
        'manufactroversy': ('manufacture', 'controversy'),
        'masstige': ('mass market', 'prestige'),
        'multiplex': ('multiple', 'complex'),
        'petrodollar': ('petroleum', 'dollar'),
        'prosumer': ('producer', 'consumer'),
        'subvertising': ('subverting', 'advertising'),
        'telemarketing': ('telephone', 'marketing'),
        'tenderpreneur': ('tendering', 'entrepreneur'),
        'wantrepreneur': ('want', 'entrepreneur'),
    },
    'Organizations and Companies': {
        'Accenture': ('accent', 'future'),
        'Alitalia': ('Ali', 'Italia'),
        'Alstom': ('Alsace', 'Thompson-Houston'),
        'Amtrak': ('American', 'track'),
        'Austar': ('Australia', 'star'),
        'Bapes': ('bathing', 'ape'),
        'Binance': ('binary', 'finance'),
        'Calutron': ('California University Cyclotron',),
        'Carvana': ('car', 'nirvāṇa'),
        'Citigroup': ('Citicorp', 'Travelers Group'),
        'Citizendium': ("Citizens' Compendium",),
        'Comcast': ('communication', 'broadcast'),
        'Compaq': ('compatibility', 'quality'),
        'Conservapedia': ('conservative', 'Wikipedia'),
        'Creamsicle': ('cream', 'popsicle'),
        'Danimals': ('Dannon', 'animals'),
        'Dash (cryptocurrency)': ('Digital', 'Cash'),
        'Ecosia': ('ecology', 'Acacia'),
        'Edexcel': ('educational', 'excellence'),
        'Emergen-C': ('emergency', 'vitamin C'),
        'Extell': ('excellence', 'intelligence'),
        'Froogle': ('frugal', 'Google'),
        'Fruitopia': ('fruit', 'utopia'),
        'Fudgsicle': ('fudge', 'popsicle'),
        'Funimation': ('fun', 'animation'),
        'Garmin': ('Gary Burrell', 'Min Kao'),
        'Googleplex': ('Google', 'complex'),
        'Groupon': ('group', 'coupon'),
        'Ideanomics': ('idea', 'economics'),
        'Imagineering': ('Imagine', 'Engineering'),
        'LATAM': ('Lan Airlines', 'TAM Airlines'),
        'Lenovo': ('Legend', 'novo'),
        'Medi-Cal': ('medical', 'California'),
        'Medicaid': ('medicine', 'aid'),
        'Medicare': ('medicine', 'care'),
        'Netflix': ('internet', 'flicks'),
        'Nikon': ('Nippon Kōgaku', 'Ikon'),
        'Pinterest': ('pin', 'interest'),
        'Poo-Pourri': ('poo', 'potpourri'),
        'Popsicle': ('pop or lollipop', 'Epsicle'),
        'Qualcomm': ('Quality', 'Communications'),
        'RuPay': ('rupee', 'payment'),
        'Rustoleum': ('rust', 'linoleum'),
        'Spotify': ('spot', 'identify'),
        'Teletoon': ('television', 'cartoon'),
        'Toonami': ('cartoon', 'tsunami'),
        'Toshiba': ('Shibaura Seisaku-sho', 'Tokyo Denki'),
        'Travelocity': ('travel', 'velocity'),
        'Triscuit': ('electricity', 'biscuit'),
        'Venezuelanalysis': ('Venezuela', 'analysis'),
        'Verizon': ('veritas', 'horizon'),
        'Victorinox': ('Victoria', 'inox'),
        'Unilever': ('Margarine Unie', 'Lever Brothers'),
        'Wikimedia': ('Wikipedia', 'media'),
        'Wikipedia': ('wiki', 'encyclopedia'),
        'Yelp': ('yellow pages', 'help'),
        'Yosicle': ('yogurt', 'popsicle'),
    },
    "Places": {
    'AfPak': ('Afghanistan', 'Pakistan'),
    'Afrabia': ('Africa', 'Arabia'),
    'Afro-Eurasia': ('Africa', 'Europe', 'Asia'),
    'Arlandria': ('Arlington, VA', 'Alexandria, VA'),
    'Australasia': ('Australia', 'Asia'),
    'Autopia': ('automobile', 'utopia'),
    'Benelux': ('Belgium', 'Netherlands', 'Luxembourg'),
    'Birome': ('Bickham', 'Jerome Cartwright'),
    'BosWash': ('Boston', 'Washington, D.C.'),
    'Brockton': ('Brant', 'Greenock', 'Walkerton'),
    'Calexico': ('California', 'Mexico'),
    'Calistoga': ('California', 'Saratoga'),
    'Canwood': ('Canadian', 'woodlands'),
    'Chambana': ('Champaign', 'Urbana'),
    'Chiberia': ('Chicago', 'Siberia'),
    'Chindia': ('China', 'India'),
    'Chiraq': ('Chicago', 'Iraq'),
    'Chimerica': ('China', 'America'),
    'Clerval': ('claire vallée', '"clear valley"'),
    'Cotai': ('Coloane', 'Taipa'),
    'Czechoslovakia': ('Czechia', 'Slovakia'),
    'Dalworthington Gardens': ('Dallas', 'Fort Worth', 'Arlington'),
    'Delmarva': ('Delaware', 'Maryland', 'Virginia'),
    'Delran Township': ('Delaware River', 'Rancocas Creek'),
    'Donbas': ('Donets coal basin',),
    'Eurabia': ('Europe', 'Arabia'),
    'Eurasia': ('Europe', 'Asia'),
    'Fairborn': ('Fairfield', 'Osborn'),
    'Glenbard': ('Glen Ellyn', 'Lombard'),
    'Harvey Cedars': ('harvest', 'cedars'),
    'Hillcrest': ('Country Club Hills', 'Hazel Crest'),
    'Hollansburg': ('Hollaman', 'Harland', 'landowners'),
    'Hotlanta': ('hot', 'Atlanta'),
    'Illiana': ('Illinois', 'Indiana'),
    'Indialantic': ('Indian River Lagoon', 'Atlantic Ocean'),
    'Irrigon': ('irrigation', 'Oregon'),
    'Jardee': ('Jardanup', 'Deeside'),
    'Kanorado': ('Kansas', 'Colorado'),
    'Kanwaka Township and Kanwaka': ('Kansas', 'Wakarusa Rivers'),
    'Kentuckiana': ('Kentucky', 'Indiana'),
    'Kormak': ('Charles Korpela', 'Oscar Maki', 'settlers'),
    'Manchattan': ('Manchester', 'Manhattan'),
    'Mexicali': ('Mexico', 'California'),
    'Michiana': ('Michigan', 'Indiana'),
    'Navelencia': ('navel', 'Valencia oranges'),
    'NyLon': ('New York City', 'London'),
    'Nylonkong': ('New York City', 'London', 'Hong Kong'),
    'Ohaton': ('Osler', 'Hammond', 'Nanton company'),
    'Pennsyltucky': ('Pennsylvania', 'Kentucky'),
    'Poictesme': ('Poitiers', 'Angoulême'),
    'Sauk Prairie': ('Sauk City', 'Prairie du Sac'),
    'Scarberia': ('Scarborough', 'Siberia'),
    'SeaTac and Sea-Tac Airport': ('Seattle', 'Tacoma'),
    'Stravenue': ('street', 'avenue'),
    'Tamiami': ('Tampa', 'Miami'),
    'Tanzania': ('Tanganyika', 'Zanzibar'),
    'Taxachusetts': ('taxation', 'Massachusetts'),
    'Texarkana': ('Texas', 'Arkansas', 'Louisiana'),
    'Texoma': ('Texas', 'Oklahoma'),
    'The Tridge': ('Tri-Cities', 'bridge'),
    'Valsetz': ('Valley', 'Siletz Railroad', 'ghost town'),
    'Vansterdam': ('Vancouver', 'Amsterdam'),
    'WaKeeney': ('Warren', 'Keeney', '& Co.'),
    'Willowick': ('Willoughby', 'Wickliffe', 'OH'),
    'Woolaroc': ('woods', 'lakes', 'rocks')}
}

topic = random.choice(list(portmanteaus))
word = random.choice(list(portmanteaus[topic]))
root1 = portmanteaus[topic][word][0]
root2 = portmanteaus[topic][word][1]

print(topic)
print(word)
print(root1)
print(root2)